### ISSUE TITLE
Provide .exe version of (Python 2 supported) write-plus-plus application

### ISSUE THREAD

**Issue by harshagv** [t1m0thyj/write-plus-plus#1]
Please provide **# .exe version of write++** (Python 2 supported), where it had complete feature rich application including filter function and launcher frame.

**Comment by t1m0thyj** [comment]
The only EXE version I have been able to find on my computer is bundled in an installer. I would provide just a ZIP file if I could, but here's a link to download the installer: https://drive.google.com/open?id=12cRYh3pi56eXFrqOJibMecx3eFppNOLk. There are still several features that I never got to complete, especially the Style Editor.
